[package]
name = "fontutil"
version = "0.1.0"
authors = ["hikir1 <hikirone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

font-kit = "0.7.0"