[package]
name = "block"
version = "0.1.0"
authors = ["hikir1 <hikirone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

printpdf = "0.3.2"
logos = "0.11.4"