
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAR ENDPARA SPACEcodex          : paragraph codex\n\t   paragraph      : word paragraph\n\t   last_paragraph : word last_paragraph\n\t   word           : CHAR word\n\t   last_word      : CHAR last_wordcodex : last_paragraphparagraph      : last_word ENDPARA\n\t   last_paragraph : last_wordword      : SPACE\n\t   last_word :'
    
_lr_action_items = {'CHAR':([0,2,4,6,7,9,11,12,],[6,6,6,6,-9,-2,-7,-4,]),'SPACE':([0,2,4,6,7,9,11,12,],[7,7,7,7,-9,-2,-7,-4,]),'ENDPARA':([0,2,4,5,6,7,9,11,12,13,],[-10,-10,-10,11,-10,-9,-2,-7,-4,-5,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,],[-10,0,-10,-6,-10,-8,-10,-9,-1,-2,-3,-7,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'codex':([0,2,],[1,8,]),'paragraph':([0,2,4,],[2,2,9,]),'last_paragraph':([0,2,4,],[3,3,10,]),'word':([0,2,4,6,],[4,4,4,12,]),'last_word':([0,2,4,6,],[5,5,5,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> codex","S'",1,None,None,None),
  ('codex -> paragraph codex','codex',2,'p_prepend','parser.py',15),
  ('paragraph -> word paragraph','paragraph',2,'p_prepend','parser.py',16),
  ('last_paragraph -> word last_paragraph','last_paragraph',2,'p_prepend','parser.py',17),
  ('word -> CHAR word','word',2,'p_prepend','parser.py',18),
  ('last_word -> CHAR last_word','last_word',2,'p_prepend','parser.py',19),
  ('codex -> last_paragraph','codex',1,'p_codex_end','parser.py',24),
  ('paragraph -> last_word ENDPARA','paragraph',2,'p_paragraph_end','parser.py',30),
  ('last_paragraph -> last_word','last_paragraph',1,'p_paragraph_end','parser.py',31),
  ('word -> SPACE','word',1,'p_word_end','parser.py',37),
  ('last_word -> <empty>','last_word',0,'p_word_end','parser.py',38),
]
